//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormProEF
{
    using System;
    
    public enum ColorNameList : int
    {
        Red = 1,
        Yellow = 2,
        Blue = 3,
        Green = 4,
        Gray = 5,
        Pink = 6
    }
}
