//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormProEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerId { get; set; }
        public string FullName { get; set; }
        public string FirstAddr { get; set; }
        public string SecondAddr { get; set; }
        public string City { get; set; }
        public string State_Province { get; set; }
        public string Region_Country { get; set; }
        public Nullable<ColorNameList> FavColor { get; set; }
    }
}
