//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstTest1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public System.Guid AdminID { get; set; }
        public string Name { get; set; }
        public int dept { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
    }
}
